### ISSUE TITLE
Support basic install

### ISSUE THREAD

**Issue by ChronosWS** [ChronosWS/asma#1]
The application need to support basic server installation.  This includes:
[X]  Acquiring SteamCMD
✅  Downloading the ASA project
[X]  Setting critical server values such as ports and passwords
[X]  Starting and stopping the server

**Comment by Natclanwy** [comment]
Forcing the server installation to the root directory will be important, that simple change reduced the number of support issues for ASM by an order of magnitude due to excessive file path length.

**Comment by ChronosWS** [comment]
> Forcing the server installation to the root directory will be important, that simple change reduced the number of support issues for ASM by an order of magnitude due to excessive file path length.

Well that explains why the ASM didn't allow choosing an arbitrary path!  I was wondering...

**Comment by ChronosWS** [comment]
This is now fully supported in master.  Critical values must be enabled in Metadata and then set for the servers.
