### ISSUE TITLE
Use friendly name rather than guid for server folder names

### ISSUE THREAD

**Issue by ChronosWS** [ChronosWS/asma#13]
It can be hard to see in File Explorer which server you are dealing with outside of ASM.  Also guids are long which could lead to path length issues in some circumstances.

**Comment by Alucard06660** [comment]
First potential problem that I see is in server settings, it is this imposed and non-changeable "Id" which defines the name of the installation folders.
Let's say that personal opinion it is not super intuitive for potential Clsuter or just multi-server to find in the files and potential problem of path length which was present on ASE and ASM.
This also makes it more "complicated" to set up ASMA on an already existing server, even if nothing insurmountable of course, just copy and paste your Saved folder into the new server created with ASMA, but let's say it requires having to reinstall and remove the old one.
I think that keep "Id" for the name of the profile why even if not intuitive for the profile search, but at least allow you to define the name of the installation folder in this "Id"I think that keep "Id" for the profile name why even if not intuitive for profile search, but at least allow to define the name of the installation folder which does not use "Id"
