### ISSUE TITLE
FEATURE: ServerApi integration

### ISSUE THREAD

**Issue by Lacoi** [ChronosWS/asma#36]
With ServerApi installed, the server musto be startet by `AsaApiLoader.exe`. After initialization, the ArkApi starts the `ArkAscendedServer.exe` with the same command args.
Link to ServerApi: https://gameservershub.com/forums/resources/ark-survival-ascended-serverapi-crossplay-supported.683/

**Comment by ChronosWS** [comment]
This work depends on #37
