### ISSUE TITLE
Feature: -dev in mod ids

### ISSUE THREAD

**Issue by The-God-Of-Noise** [ChronosWS/asma#56]
to be able to either Write -dev at the end of the mod ID or have a checkbox that tells ASMA to put it there by it self 

i see the reason to only allow numbers in the mod id fields but as modders we need the option to have the -dev argument at the end of the mod id so the server downloads the latest unpublished version of the mod so we can test our mods on servers 

the checkbox option would be best imo so people cant write what ever they want and confuse the system 
and the -dev is not a thing that will change so it will always be either just the mod id or the mod id + -dev

hope it makes sense

**Comment by The-God-Of-Noise** [comment]
as long as the -dev comes right after the project id it dosent matter from what i know 
that part is just for mod load order i would think 

but a checkbox next to the remove button or something that if it is checked it adds -dev after the id would work :) 
would also prevent people writing what ever they want in the id field :)

**Comment by DarkMatter8998** [comment]
i also need this as i'm a tester for mods and need this so we dont have to pay dicktrado for a server to use the dev ver of a mod in testing
