### ISSUE TITLE
Possibility of using 3rd party tools for gameusersettings.ini and game.ini

### ISSUE THREAD

**Issue by 8Ac3** [ChronosWS/asma#7]
As mentioned in Discord an option to use a 3rd party tool such as Beacon to manage the settings files and use ASMA for server management. Looking at ASM it appears Beacon does pretty much the same job, but has a few nice to have options. Cloud saves, Community sharing of "projects", built in calculators for day/night cycle, breeding multipliers, preset engram control options.

TBH, I am new to Beacon after thinking that ASMA may not continue so I am no expert by any means, but a few of the features above are quite nice and if they could be replicated/improved on in ASMA then that is perfect and if not then a check box/button to say these settings are managed elsewhere would also be great.

**Comment by ChronosWS** [comment]
We support an option called "External INI Mangement" for each server, which will cause ASMA to only set values which are explicitly overridden, rather than removing all values which are not managed by ASMA.
